# Generated by Django 5.1.5 on 2025-01-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bg', 'Bugatti'), ('lb', 'Lamborghini'), ('fr', 'Ferrari'), ('rr', 'Rolls-Royce'), ('pc', 'Porsche'), ('ml', 'McLaren')], max_length=2),
        ),
    ]
