# Generated by Django 5.1.5 on 2025-01-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bg', 'Bugatti'), ('lb', 'Lamborghini'), ('fr', 'Ferrari'), ('rr', 'Rolls-Royce'), ('pc', 'Porsche'), ('ml', 'McLaren')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
