# Generated by Django 4.0.6 on 2025-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, help_text='First and Last name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_no',
            field=models.CharField(blank=True, help_text='Flat, House no., Building, Company, Apartment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark (Optional)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, help_text='6 digits code', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, help_text='Area, Street, Sector, Village', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, help_text='Town/City', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], help_text='Choose a state', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
